import type { MetadataRoute } from "next";

/* Canonical, indexable 200s only. /thank-you (noindex) and redirect
   sources are excluded. The Kansas City page, when built, appears here
   and NOWHERE in nav or footer, per the addendum. */

const BASE = "https://cardinalfoundationservices.com";

const PATHS: { path: string; priority: number }[] = [
  { path: "/", priority: 1 },
  { path: "/residential/", priority: 0.9 },
  { path: "/commercial/", priority: 0.9 },
  { path: "/new-construction/", priority: 0.8 },
  { path: "/services/commercial-foundation-repair/", priority: 0.9 },
  { path: "/commercial/tilt-wall/", priority: 0.9 },
  { path: "/commercial/concrete-lifting/", priority: 0.7 },
  { path: "/commercial/concrete-lifting/warehouse-floor-leveling/", priority: 0.8 },
  { path: "/commercial/due-diligence-walks/", priority: 0.8 },
  { path: "/residential/foundation-repair/", priority: 0.9 },
  { path: "/residential/foundation-repair/steel-piers/", priority: 0.9 },
  { path: "/residential/foundation-repair/drilled-piers/", priority: 0.8 },
  { path: "/residential/foundation-repair/post-tension-slab-repair/", priority: 0.8 },
  { path: "/residential/concrete-leveling/", priority: 0.7 },
  { path: "/residential/concrete-leveling/polyurethane-foam-injection/", priority: 0.8 },
  { path: "/residential/concrete-leveling/mudjacking/", priority: 0.7 },
  { path: "/residential/drainage/", priority: 0.8 },
  { path: "/residential/drainage/french-drains/", priority: 0.8 },
  { path: "/resources/pier-systems-explained/", priority: 0.8 },
  { path: "/commercial/foundation-repair/steel-piers/", priority: 0.8 },
  { path: "/commercial/multifamily/", priority: 0.8 },
  { path: "/commercial/concrete-construction/", priority: 0.6 },
  { path: "/commercial/drainage/", priority: 0.6 },
  { path: "/commercial/retaining-walls/", priority: 0.6 },
  { path: "/commercial/specialty/", priority: 0.6 },
  { path: "/residential/retaining-walls/", priority: 0.8 },
  { path: "/new-construction/concrete-flatwork/", priority: 0.7 },
  { path: "/new-construction/earthwork-grading/", priority: 0.7 },
  { path: "/locations/", priority: 0.7 },
  { path: "/locations/fort-worth/", priority: 0.9 },
  { path: "/locations/dallas/", priority: 0.9 },
  { path: "/locations/houston/", priority: 0.9 },
  { path: "/locations/possum-kingdom-lake/", priority: 0.7 },
  { path: "/commercial/foundation-repair/underpinning/", priority: 0.7 },
  { path: "/commercial/foundation-repair/drilled-piers/", priority: 0.7 },
  { path: "/commercial/foundation-repair/helical-piers-tiebacks/", priority: 0.7 },
  { path: "/commercial/foundation-repair/hybrid-piers/", priority: 0.7 },
  { path: "/commercial/foundation-repair/post-tension-repair/", priority: 0.7 },
  { path: "/commercial/concrete-lifting/polyurethane-foam-injection/", priority: 0.7 },
  { path: "/commercial/concrete-lifting/mudjacking/", priority: 0.6 },
  { path: "/commercial/concrete-lifting/municipal/", priority: 0.6 },
  { path: "/commercial/concrete-construction/slab-pouring/", priority: 0.7 },
  { path: "/commercial/concrete-construction/slab-repair/", priority: 0.7 },
  { path: "/commercial/concrete-construction/expansion-joint-mastic-repair/", priority: 0.6 },
  { path: "/commercial/concrete-construction/structural-crack-repair/", priority: 0.6 },
  { path: "/commercial/drainage/perimeter-drainage/", priority: 0.6 },
  { path: "/commercial/drainage/french-drains/", priority: 0.6 },
  { path: "/commercial/retaining-walls/structural-repair/", priority: 0.6 },
  { path: "/commercial/retaining-walls/tieback-anchors/", priority: 0.6 },
  { path: "/commercial/structural-repair/", priority: 0.7 },
  { path: "/commercial/specialty/parking-garage-repair/", priority: 0.6 },
  { path: "/commercial/specialty/lube-pit-foundation-repair/", priority: 0.6 },
  { path: "/commercial/specialty/metal-deck-slab-repair/", priority: 0.6 },
  { path: "/commercial/specialty/balcony-repair/", priority: 0.6 },
  { path: "/commercial/specialty/lightweight-concrete-repair/", priority: 0.6 },
  { path: "/commercial/specialty/historical-building-foundation-repair/", priority: 0.6 },
  { path: "/commercial/specialty/waterproofing/", priority: 0.6 },
  { path: "/commercial/specialty/waters-of-the-us/", priority: 0.6 },
  { path: "/residential/foundation-repair/concrete-pressed-piers/", priority: 0.8 },
  { path: "/residential/foundation-repair/helical-piers/", priority: 0.7 },
  { path: "/residential/foundation-repair/hybrid-piers/", priority: 0.7 },
  { path: "/residential/foundation-repair/slab-repair/", priority: 0.8 },
  { path: "/residential/foundation-repair/pier-and-beam/", priority: 0.8 },
  { path: "/residential/drainage/area-drains/", priority: 0.6 },
  { path: "/residential/drainage/root-barriers/", priority: 0.6 },
  { path: "/residential/drainage/sump-pumps/", priority: 0.6 },
  { path: "/residential/drainage/hydrostatic-testing/", priority: 0.6 },
  { path: "/request/", priority: 0.7 },
  { path: "/warranty/", priority: 0.5 },
  { path: "/financing/", priority: 0.6 },
  { path: "/residential/concrete-leveling/concrete-crack-repair/", priority: 0.6 },
  { path: "/projects/tilt-wall-foundation-drainage-restoration/", priority: 0.6 },
  { path: "/projects/steel-piers-n-stemmons/", priority: 0.6 },
  { path: "/projects/diplomat-drive-polyurethane-injection-industrial-foundation-lift-void-fill/", priority: 0.6 },
  { path: "/projects/baytown-multi-family/", priority: 0.6 },
  { path: "/projects/lewisville-tx-multi-family-pier-stabilization-foundation-lifting-and-drainage-repair/", priority: 0.6 },
  { path: "/projects/multi-family-foundation-repair-in-austin-tx/", priority: 0.6 },
  { path: "/projects/multifamily-foundation-repair-carrollton-tx/", priority: 0.6 },
  { path: "/projects/restaurant-foundation-repair-foam-injection/", priority: 0.6 },
  { path: "/projects/commercial-foundation-stabilization-creekside-erosion-repair/", priority: 0.6 },
  { path: "/projects/", priority: 0.7 },
  { path: "/about/", priority: 0.6 },
  { path: "/contact/", priority: 0.6 },
  { path: "/privacy-policy/", priority: 0.1 },
];

export default function sitemap(): MetadataRoute.Sitemap {
  return PATHS.map(({ path, priority }) => ({
    url: BASE + path,
    lastModified: new Date(), // build date
    changeFrequency: "monthly",
    priority,
  }));
}
